### ISSUE TITLE
Can't install, missing SESSION_SECRET env var

### ISSUE THREAD

**Issue by DarrenN** [jonase/cljsfiddle#5]
Would like to help with UI issues, but cannot install locally as I don't know what to set the SESSION_SECRET env var to https://github.com/jonase/cljsfiddle/blob/master/src/clj/cljsfiddle/handler.clj#L27

**Comment by jonase** [comment]
try something like

```
 export SESSION_SECRET=[16 random chars]
```

**Comment by DarrenN** [comment]
Great thanks, that did the trick.
